language: c # Use python installtion provided by miniconda
env:
  matrix:
    - PYTHON_VERSION=2.7 CONDA_PY=27 BUILD_DOCS=1
    - PYTHON_VERSION=3.4 CONDA_PY=34 BUILD_DOCS=0
  global:
    - BINSTAR_USER=bjodah
    - GITHUB_USER=bjodah
    - GITHUB_REPO=pybestprac
    # TOKENS for github and binstar:
    - secure: "VenwDZD7KH+YG/QSrkVyiQ7vZjCGHM29V43VXLJqaEx93Bg8M8wKGhKXtiTVqvlzGbR+vUkLHlyk8WXP63Dp3qqpzdwBkEI3Crfq7hU9j/S4d7xjTSu3icXmMBFOjidE9SIp/5y0i5XmyA/N7m/hcOWZf33TDNL/Rx2BMZRa8TQ="
    - secure: "JnLHNyHwgjzIKdZ4MdJm98IjAoUjN6eZ3SyGw629ad7BMM8P1n/tPlwDd6WuVQHvVpkVsnoEhg45CsC4vIg+wXVpfjfqSC9kQtPnvdDMEsDwxCG4soKrH5HJVjp6XsY6RbtutqQgDsp7+bYl6edL+r7GzDx39cb+pk2fE0H/OBo="

before_install:
  - if [[ $(git log --format=%B --no-merges -n 1) =~ \w*\[release\]\w* ]]; then export IS_RELEASE=1; else export IS_RELEASE=0; fi
  - echo $IS_RELEASE
  - export CONDA_PATH=$HOME/miniconda
  - source ./scripts/install_miniconda.sh $PYTHON_VERSION $CONDA_PATH
  - conda config --add channels http://conda.binstar.org/$BINSTAR_USER
  - export ENV_NAME=pybestprac_testenv
  - ./scripts/ubuntu12.04/apt_get_gcc_48.sh
  - ./scripts/ubuntu12.04/apt_get_g++_48.sh
  - ./scripts/ubuntu12.04/apt_get_gfortran_48.sh
  - source ./scripts/setup_conda_testenv.sh $PYTHON_VERSION $ENV_NAME
  - python --version
  - python -c "import setup; print(setup.__version__)"
  - export DISTUTILS_DEBUG=1
install:
  - conda build conda-recipe
  - conda install pybestprac --use-local
  - LIBRARY_PATH=$CONDA_PATH/envs/$ENV_NAME/lib:$LIBRARY_PATH python setup.py build_ext --inplace
script: 
  - ./scripts/run_tests.sh
after_success:
  - coveralls
  - python scripts/move-conda-package.py conda-recipe
  - conda install binstar
  - binstar -t $BINSTAR_TOKEN upload --force *.tar.bz2
  - ./scripts/travis_after_success.sh
notifications:
  email: false
